# Generated by Django 4.2.15 on 2024-08-31 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='reported_by_staff',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='reported_by_student',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='reported_date',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='status',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('bullying', 'Bullying'), ('harassment', 'Harassment'), ('vandalism', 'Vandalism'), ('theft', 'Theft'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
