# Generated by Django 4.2.15 on 2024-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_incidentreport_reported_by_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='requester_name',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='resolution_date',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20, null=True),
        ),
    ]
