# Generated by Django 4.2.15 on 2024-09-07 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_event_description_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_date', models.DateField()),
                ('image', models.ImageField(upload_to='attendance_sheets/')),
                ('class_name', models.CharField(max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
