# Generated by Django 4.2.15 on 2024-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_attendanceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceimage',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
