# Generated by Django 4.2.15 on 2024-09-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_attendanceimage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceimage',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='attendanceimage',
            name='image',
        ),
    ]
