# Generated by Django 4.2.15 on 2024-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_note_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='No content provided'),
            preserve_default=False,
        ),
    ]
