# Generated by Django 4.2.15 on 2024-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, default='describe club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='students',
            field=models.ManyToManyField(to='main.student'),
        ),
        migrations.AlterField(
            model_name='club',
            name='teachers',
            field=models.ManyToManyField(to='main.teacher'),
        ),
    ]
