# Generated by Django 4.2.15 on 2024-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_timeslot_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.CharField(max_length=20),
        ),
    ]
