# Generated by Django 4.2.15 on 2025-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_timetable_subject_remove_timetable_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
