# Generated by Django 4.2.15 on 2025-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_timetable_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardians_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardians_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
