# Generated by Django 4.2.15 on 2025-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_student_guardians_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
