# Generated by Django 4.2.15 on 2025-02-26 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_incidentreport_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('bullying', 'Bullying'), ('vandalism', 'Vandalism'), ('theft', 'Theft'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolution_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved')], default='reported', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
