# Generated by Django 4.2.15 on 2025-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_incidentreport_assigned_to_incidentreport_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
