# Generated by Django 4.2.15 on 2025-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_budgetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
