# Generated by Django 4.2.15 on 2025-03-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_budget_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlog',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
