# Generated by Django 4.2.15 on 2025-03-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_budgetlog_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'level')},
        ),
    ]
