# Generated by Django 4.2.15 on 2025-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_subject_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_subjects', to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_taught',
            field=models.ManyToManyField(related_name='assigned_teachers', to='main.subject'),
        ),
    ]
